### ISSUE TITLE
Using QSPSaveEditor

### ISSUE THREAD

**Issue by elishacuthbert** [Pararock/QSPSaveEditor#1]
How do I go about using the QSPSaveEditor.
I am alien to Visual Studio. I also downloaded the Microsoft Visual Basic 2017 RC but not sure how to edit a save file.
Please let me know how can I edit a save file.

**Comment by Pararock** [comment]
You don't need Visual Studio to uses it. Visual Studio is only if you want to modify the software itself, you need to know programming for this.

Go in the [Release section](https://github.com/Pararock/QSPSaveEditor/releases/tag/0.3) and download the latest version. In this case 0.3. Extract the .7z with 7zip or winrar and run the .exe.  

Once inside the software, open the .qsp, then open the .sav and edit the variables you want.

**Comment by Pararock** [comment]
You don't need Full Visual Studio to uses it. Visual Studio is only if you want to modify the software itself, you would need to know programming for this. If you only want to run a program, you just need the right Redistributable version, in this case VC++ 2015 X86.

To use the software, go in the [Release section](https://github.com/Pararock/QSPSaveEditor/releases) and download the latest version. Extract the .7z with 7zip or winrar and run the .exe.  Don't forget to read the requirements section too.

Once inside the software, open the .qsp, then open the .sav and edit the variables you want.

**Comment by elishacuthbert** [comment]
Thanks for providing the instructions again.
I actually downloaded the file from https://github.com/Pararock/QSPSaveEditor by clicking on the Clone or download button and the instruction wasn't as clear as in https://github.com/Pararock/QSPSaveEditor/releases.
